import Link from "next/link";
import { pageMetadata } from "../page-metadata";
import { Arrow, SiteFooter, SiteHeader } from "../site-shell";

export const metadata = pageMetadata({ title: "Safety & Privacy", description: "Learn how PauseSure approaches privacy, secure processing, honest limitations, and user-controlled sharing.", path: "/safety" });

export default function SafetyPage() {
  return <><SiteHeader /><main className="inner-main" id="main-content" tabIndex={-1}>
    <section className="page-hero safety-page-hero"><div className="page-hero-copy"><p className="eyebrow"><span /> Safety & privacy</p><h1>Protection should not require surveillance.</h1><p>Suspicious messages and family relationships are sensitive. PauseSure prioritizes data minimization, explicit user action, limited retention, and honest explanations of what the product cannot know.</p><div className="hero-actions"><Link className="button button-primary" href="/security">Read security details <Arrow /></Link><Link className="button button-secondary" href="/privacy">Read the privacy notice</Link></div></div><div className="safety-seal"><span>Privacy by design</span><strong>Know less.<br/>Explain more.</strong><p>No advertising · No data selling · No silent family monitoring</p></div></section>
    <section className="section page-section"><div className="section-heading centered"><p className="section-kicker">Four commitments</p><h2>Trust is part of the product.</h2></div><div className="commitment-grid"><article><span>01</span><h3>Deliberate input</h3><p>Checks begin only when you choose an item or start a supported feature.</p></article><article><span>02</span><h3>Minimized processing</h3><p>Each feature uses the narrowest practical route and only the information required for the action you choose.</p></article><article><span>03</span><h3>User-controlled sharing</h3><p>Trusted Circle uses clear permissions, selective sharing, and the ability to leave.</p></article><article><span>04</span><h3>Honest uncertainty</h3><p>A missing warning or failed lookup is never presented as proof that something is safe.</p></article></div></section>
    <section className="data-path-section"><div><p className="section-kicker light">A legible data path</p><h2>What happens should never be a mystery.</h2></div><ol><li><span>1</span><strong>You choose</strong><p>Select a message, link, image, QR code, or supported recording.</p></li><li><span>2</span><strong>PauseSure processes</strong><p>The selected feature uses a documented processing route and only the access it needs.</p></li><li><span>3</span><strong>You decide</strong><p>Review the explanation, verify elsewhere, save a result, or share selectively.</p></li><li><span>4</span><strong>You stay in control</strong><p>Published retention and deletion rules remain part of the feature—not hidden operational details.</p></li></ol></section>
    <section className="section safety-links"><Link href="/privacy"><small>Policy</small><strong>Privacy</strong><p>What is collected, why, and the choices available to you.</p><span>Read policy →</span></Link><Link href="/security"><small>Practice</small><strong>Security</strong><p>Architecture, protection boundaries, reporting, and responsible disclosure.</p><span>Explore security →</span></Link><Link href="/account-deletion"><small>Control</small><strong>Account deletion</strong><p>How to request deletion and what the process covers.</p><span>View instructions →</span></Link></section>
    </main><SiteFooter /></>;
}
