import Link from "next/link";
import { pageMetadata } from "../page-metadata";
import { Arrow, SiteFooter, SiteHeader } from "../site-shell";

export const metadata = pageMetadata({ title: "Safety & Privacy", description: "Learn how PauseSure approaches privacy, secure processing, honest limitations, and user-controlled sharing.", path: "/safety" });

export default function SafetyPage() {
  return <><SiteHeader /><main className="inner-main" id="main-content" tabIndex={-1}>
    <section className="page-hero safety-page-hero"><div className="page-hero-copy"><p className="eyebrow"><span /> Safety & privacy</p><h1>Protection should not require surveillance.</h1><p>Suspicious messages and family relationships are sensitive. PauseSure prioritizes data minimization, explicit user action, limited retention, and honest explanations of what the product cannot know.</p><div className="hero-actions"><Link className="button button-primary" href="/security">Read security details <Arrow /></Link><Link className="button button-secondary" href="/privacy">Read the privacy notice</Link></div></div><div className="safety-seal"><span>Privacy by design</span><strong>Know less.<br/>Explain more.</strong><p>No advertising · No data selling · No silent family monitoring</p></div></section>
    <section className="section page-section"><div className="section-heading centered"><p className="section-kicker">Four commitments</p><h2>Trust is part of the product.</h2></div><div className="commitment-grid"><article><span>01</span><h3>Deliberate input</h3><p>Checks begin only when you choose an item or start a supported feature.</p></article><article><span>02</span><h3>Minimized processing</h3><p>Each feature uses the narrowest practical route and only the information required for the action you choose.</p></article><article><span>03</span><h3>User-controlled sharing</h3><p>Trusted Circle uses clear permissions, selective sharing, and the ability to leave.</p></article><article><span>04</span><h3>Honest uncertainty</h3><p>A missing warning or failed lookup is never presented as proof that something is safe.</p></article></div></section>
    <section className="section page-section" id="protection-check">
      <div className="section-heading"><p className="section-kicker">Protection setup check</p><h2>It checks setup—not your private content.</h2><p>The in-app protection check reads only the iPhone states that Apple makes available. It explains what was confirmed, what needs setup, and what must still be checked manually.</p></div>
      <div className="commitment-grid">
        <article><span>01</span><h3>Caller identification</h3><p>Checks the iOS enabled state and whether a valid, current, nonempty caller-label snapshot is loaded. It does not prove a caller is genuine; caller ID can be spoofed.</p></article>
        <article><span>02</span><h3>Message and Share extensions</h3><p>Confirms that the extensions are included in the installed app. iOS does not tell PauseSure whether Message Filter is enabled or whether Share is visible or pinned, so those checks remain manual.</p></article>
        <article><span>03</span><h3>Notifications and account</h3><p>Reads notification permission and whether an active signed-in session exists. It does not silently ping the backend or claim APNs registration, current connectivity, or delivery.</p></article>
        <article><span>04</span><h3>Strict inspection boundary</h3><p>The setup check does not inspect calls, messages, contacts, photos, links, screenshots, QR codes, or audio. It never runs a hidden scam scan.</p></article>
      </div>
    </section>
    <section className="data-path-section"><div><p className="section-kicker light">A legible data path</p><h2>What happens should never be a mystery.</h2></div><ol><li><span>1</span><strong>You choose</strong><p>Select a message, link, image, QR code, or supported recording.</p></li><li><span>2</span><strong>PauseSure processes</strong><p>The selected feature uses a documented processing route and only the access it needs.</p></li><li><span>3</span><strong>You decide</strong><p>Review the explanation, verify elsewhere, save a result, or share selectively.</p></li><li><span>4</span><strong>You stay in control</strong><p>Published retention and deletion rules remain part of the feature—not hidden operational details.</p></li></ol></section>
    <section className="section page-section" id="protection-tools">
      <div className="section-heading"><p className="section-kicker">Protection tools</p><h2>Investigate, involve, and recover.</h2><p>These are user-started tools, separate from the setup check. Each one has a defined purpose and a visible boundary.</p></div>
      <div className="commitment-grid">
        <article><span>01</span><h3>URL threat intelligence</h3><p>Checks a bounded address against Google Web Risk and keeps provider credentials on PauseSure servers. It does not open the submitted site or treat its current response status, deactivation, or later return as proof of safety. A no-known-match response never overrides stronger warning signals.</p></article>
        <article><span>02</span><h3>Screenshot recognition</h3><p>Normalizes the image you choose into a bounded JPEG or PNG, sends it through PauseSure to Google Cloud Vision for text recognition, and runs the extracted evidence through the same shared fraud engine. Valid extracted web addresses may also be checked through Google Web Risk. PauseSure does not retain the screenshot or extracted text in application data or request logs.</p></article>
        <article><span>03</span><h3>Scam Pulse</h3><p>Shows manually reviewed entries that link directly to official government sources. It is not exhaustive or real-time, and a failed feed check never means a threat is absent. <a href="/scam-pulse/v1.json">View the source-backed feed.</a></p></article>
        <article><span>04</span><h3>After-call review</h3><p>Imports only the voicemail or recording you select. PauseSure does not record cellular calls or analyze live call audio.</p></article>
        <article><span>05</span><h3>Trusted Circle</h3><p>Sends a request only after you choose the recipient and confirm what to share. Connected request content is encrypted before it leaves the device.</p></article>
        <article><span>06</span><h3>Recovery plan</h3><p>Creates a practical checklist for contacting banks and affected services, securing accounts, preserving evidence, and reporting through independently verified official routes.</p></article>
      </div>
    </section>
    <section className="section safety-links"><Link href="/privacy"><small>Policy</small><strong>Privacy</strong><p>What is collected, why, and the choices available to you.</p><span>Read policy →</span></Link><Link href="/security"><small>Practice</small><strong>Security</strong><p>Architecture, protection boundaries, reporting, and responsible disclosure.</p><span>Explore security →</span></Link><Link href="/account-deletion"><small>Control</small><strong>Account deletion</strong><p>How to request deletion and what the process covers.</p><span>View instructions →</span></Link></section>
    </main><SiteFooter /></>;
}
