import Link from "next/link";
import { pageMetadata } from "../page-metadata";
import { releaseMessaging } from "../release";
import { Arrow, SiteFooter, SiteHeader } from "../site-shell";

export const metadata = pageMetadata({ title: "Company", description: "Learn about PauseSure's mission, operating principles, product status, and contact information.", path: "/company" });

export default function CompanyPage() {
  return <><SiteHeader /><main className="inner-main" id="main-content" tabIndex={-1}>
    <section className="page-hero company-page-hero"><div className="page-hero-copy"><p className="eyebrow"><span /> Company</p><h1>Technology for the pause between pressure and action.</h1><p>PauseSure develops consumer decision support for moments when urgency, uncertainty, and trust collide. The goal is simple: help people keep control long enough to verify what is real.</p></div><div className="company-manifesto"><small>Our principles</small><strong>Calm over panic.<br/>Evidence over confidence theater.<br/>Agency over surveillance.</strong></div></section>
    <section className="section company-story"><div><p className="section-kicker">Why PauseSure</p><h2>Scam protection should continue after detection.</h2></div><div><p>Many tools stop at a label. Real people still have to decide whether to answer, pay, click, call back, tell a relative, or start recovery. PauseSure is organized around that decision—not only the scan.</p><p>PauseSure is built for individuals who want a calm second opinion and families who want to help while preserving dignity and independence.</p></div></section>
    <section className="values-section"><article><span>01</span><h3>Explain the evidence</h3><p>Show why something is concerning and what remains uncertain.</p></article><article><span>02</span><h3>Reduce the blast radius</h3><p>Limit collection, access, sharing, and retention to what the chosen feature needs.</p></article><article><span>03</span><h3>Respect the person</h3><p>Design family support as consent-based assistance, not invisible monitoring.</p></article><article><span>04</span><h3>Earn every claim</h3><p>Published promises, App Store disclosures, and shipped behavior must agree.</p></article></section>
    <section className="section status-section" id="availability"><div><p className="section-kicker">Availability</p><h2>Official iPhone availability.</h2><p>{releaseMessaging.availability} Product, privacy, security, and App Store claims are reviewed together before the public download action changes.</p></div><div className="status-card"><span className="status-dot" /><div><small>{releaseMessaging.statusLabel}</small><strong>{releaseMessaging.statusValue}</strong></div></div></section>
    <section className="contact-section" id="contact"><div><p className="section-kicker light">Official routes</p><h2>Start from pausesure.com.</h2><p>Use these verified PauseSure pages for availability, product help, privacy controls, and security guidance. Never trust a contact or download route supplied only inside an urgent message.</p></div><div className="contact-options"><Link href="/company#availability"><small>iPhone release</small><strong>Official availability status</strong><Arrow /></Link><Link href="/support"><small>Help</small><strong>Support boundaries and next steps</strong><Arrow /></Link><Link href="/security"><small>Security</small><strong>Responsible disclosure guidance</strong><Arrow /></Link></div></section>
    </main><SiteFooter /></>;
}
