import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, SiteFooter, SiteHeader } from "../site-shell";

export const metadata: Metadata = { title: "Company", description: "Learn about PauseSure's mission, operating principles, product status, and contact information.", alternates: { canonical: "/company" } };

export default function CompanyPage() {
  return <><SiteHeader /><main className="inner-main" id="main-content" tabIndex={-1}>
    <section className="page-hero company-page-hero"><div className="page-hero-copy"><p className="eyebrow"><span /> Company</p><h1>Technology for the pause between pressure and action.</h1><p>PauseSure is building consumer decision support for moments when urgency, uncertainty, and trust collide. The goal is simple: help people keep control long enough to verify what is real.</p></div><div className="company-manifesto"><small>Our direction</small><strong>Calm over panic.<br/>Evidence over confidence theater.<br/>Agency over surveillance.</strong></div></section>
    <section className="section company-story"><div><p className="section-kicker">Why PauseSure</p><h2>Scam protection should continue after detection.</h2></div><div><p>Many tools stop at a label. Real people still have to decide whether to answer, pay, click, call back, tell a relative, or start recovery. PauseSure is organized around that decision—not only the scan.</p><p>The product is being developed for individuals who want a calm second opinion and families who want to help while preserving dignity and independence.</p></div></section>
    <section className="values-section"><article><span>01</span><h3>Explain the evidence</h3><p>Show why something is concerning and what remains uncertain.</p></article><article><span>02</span><h3>Reduce the blast radius</h3><p>Limit collection, access, sharing, and retention to what the chosen feature needs.</p></article><article><span>03</span><h3>Respect the person</h3><p>Design family support as consent-based assistance, not invisible monitoring.</p></article><article><span>04</span><h3>Earn every claim</h3><p>Published promises, App Store disclosures, and shipped behavior must agree.</p></article></section>
    <section className="section status-section"><div><p className="section-kicker">Product status</p><h2>In active development and testing.</h2><p>PauseSure is not yet presented as generally available. Launch timing will be published only after product, privacy, security, and App Store release gates are complete.</p></div><div className="status-card"><span className="status-dot" /><div><small>Current stage</small><strong>Private development and device testing</strong></div></div></section>
    <section className="contact-section" id="contact"><div><p className="section-kicker light">Contact</p><h2>Talk with PauseSure.</h2><p>For product questions, partnerships, accessibility feedback, or security reporting, use the appropriate channel below. Never email passwords, payment details, verification codes, or sensitive case evidence.</p></div><div className="contact-options"><a href="mailto:hello@pausesure.com"><small>General and partnerships</small><strong>hello@pausesure.com</strong><Arrow /></a><a href="mailto:security@pausesure.com"><small>Security reports</small><strong>security@pausesure.com</strong><Arrow /></a><Link href="/support"><small>Product help</small><strong>Support boundaries and guidance</strong><Arrow /></Link></div></section>
    </main><SiteFooter /></>;
}
